services:
  nzcvm_webapp_backend:
    build:
      context: . # Build context is the root directory
      dockerfile: docker/nzcvm_webapp_backend/Dockerfile # Path to the backend Dockerfile
    container_name: nzcvm_webapp_backend # Updated container name
    # No ports exposed directly to host; Nginx will proxy
    # Optional: Add volumes for development to sync code without rebuilding
    # volumes:
    #   - ./app.py:/app/app.py
    volumes:
      - /home/arr65/src/velocity_modelling/velocity_modelling/data:/usr/local/lib/python3.12/site-packages/velocity_modelling/data # Mount local data directory to package data location
    networks:
      - nzcvm_network

  nzcvm_webapp_frontend:
    build:
      context: . # Build context is the root directory
      dockerfile: docker/nzcvm_webapp_frontend/Dockerfile # Path to the frontend Dockerfile
    container_name: nzcvm_webapp_frontend
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Nginx)
    depends_on:
      - nzcvm_webapp_backend
    # Optional: Add volumes for development to sync frontend code
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html
    #   - ./css:/usr/share/nginx/html/css
    #   - ./js:/usr/share/nginx/html/js
    #   - ./data:/usr/share/nginx/html/data
    #   - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # Mount config for easy changes
    networks:
      - nzcvm_network

networks:
  nzcvm_network:
    driver: bridge
